### ISSUE TITLE
 Add Option to Handle Unknown Types Gracefully

### ISSUE THREAD

**Issue by AlexanderMint** [g4s8/envdoc#40]
Hello!

I've encountered an issue while using envdoc with a configuration structure that includes fields with types not directly supported or resolvable by envdoc, such as custom or external types. Specifically, the following scenario results in an error:

```go
package config

import "github.com/rs/zerolog"

//go:generate go run github.com/g4s8/envdoc@latest -output environments.md -types='*'

type Config struct {
    Level zerolog.Level `env:"LOG_LEVEL"  envDefault:"disabled"`
}
```

Running `envdoc` produces the following error:

```
Failed to resolve type "zerolog.Level"
```

**Proposed Solution:**

I propose modifying envdoc to suppress errors about unknown types by default and only display them when the existing -debug flag is enabled. This approach ensures:

- Non-Intrusive Default Behavior: The tool continues processing and skips fields with unknown types without disrupting the generation process.
- Error Visibility in Debug Mode: Developers who need detailed feedback can enable the -debug flag to see errors about unknown types.

I believe this feature could significantly enhance the usability of envdoc for a broader range of Go projects. I’d be happy to help further refine or implement this functionality if needed.

**Comment by g4s8** [comment]
Thanks for reporting. I partially agree with you - if the field type is just a target for env value, then we can ignore this error, because it's not important for documentation generator. But in case if it's an env-prefixed field with external struct field, then we get a problem, because we will not generate documentation for it's fields. See two examples below:

**Not a problem**
```
package config

import "github.com/rs/zerolog"

//go:generate go run github.com/g4s8/envdoc@latest -output environments.md -types='*'

type Config struct {
    Level zerolog.Level `env:"LOG_LEVEL"  envDefault:"disabled"`
}
```

**Issue with type resolving**

External file `example.com/lib/config.go`
```
package lib

type Config struct {
  Host string `env:"HOST"`
  Port int    `env:"PORT"`
}
```

Local file:
```
import "example.com/lib"

type Config struct {
  Server lib.Config `envPrefix:"SERVER_"`
}
```
---

Second example should generate documentation for:
 - `SERVER_HOST`
 - `SERVER_PORT`
But due to type resolution error, it won't do it.

So I disabled the warning for all not env-prefixed types, and added explicit `WARNING` message for second case.
